### ISSUE TITLE
накатываем базку

### ISSUE THREAD

**Issue by MikhailMe** [MikhailMe/kotoed-plugin#11]
а) Дропнуть уже существующую базку - для этого нужно подключиться к ней  
psql -U kotoed
просит пароль - вводим: kotoed
и выполнить следующие команды
drop schema public cascade;
create schema public;
\q

ЕСЛИ ВДРУГ НЕ ПОЛУЧИЛОСЬ И ПИШЕТ ЧТО-ТО ПРО owner, то выполняем следующие команды:
\q
psql -U postgres kotoed
попросит пароль - вводим: postgres
далее выполняем
drop schema public cascade;
\q
потом опять входим в kotoed:
psql -U kotoed
просит пароль - kotoed
выполняем 
create schema public;
\q

б) Теперь надо залить дамп
 базки - для этого переходим в директорию куда скачали файлик и выполняем команду:
pg_restore --format custom --single-transaction --disable-triggers -d kotoed -U postgres test-data-anon.custom

УРА - мы теперь можем тыркаться в базку котоеда, как минимум по SQL, как максимум через rest+eventbus

**Comment by vovasq** [comment]
done

**Comment by oskolkovlad** [comment]
done too

**Comment by LegkunBoris** [comment]
done

**Comment by HightMike** [comment]
done of course
